<?php

namespace App\Tests\User;

require_once __DIR__ . "/../bootstrap.php";

use App\FacadeException;
use App\Tests\BaseTestCase;
use App\User\UserFacade;
use App\User\UserFacadeFactory;
use Nette\Security\User;
use Tester\Assert;


\Tester\Environment::lock("database", TEMP_TEST);

class Sign extends BaseTestCase
{


    /** @var UserFacade */
    protected $facade;

    /** @var User */
    protected $loggedUser;



    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->facade = $this->container->getByType(UserFacadeFactory::class)->create();
    }



    public function testSignInSuccess()
    {
        $this->loggedUser = $this->facade->login("dusan.mlynarcik@email.cz", "hesloHESLO123", $this->container->getByType(User::class));

        Assert::type(User::class, $this->loggedUser);
    }



    public function testSignInFail()
    {
        $facade = $this->facade;

        Assert::exception(function () use ($facade) {
            $facade->login("dusan.mlynarcik2@email.cz", "hesloHESLO123456", $this->container->getByType(User::class));
        }, FacadeException::class);
    }



    public function testSignOut()
    {
        $this->testSignInSuccess();
        $this->facade->logout($this->loggedUser);

        Assert::null($this->loggedUser->getId());
    }
}

(new Sign())->run();