<?php

$messages['cs'] = [
    'title' => 'Chyba serveru',
    'h1' => 'Něco se pokazilo',
    'description' => 'O chybě ale už víme a pracujeme na nápravě.',
    'action' => [
        'title' => 'Co teď?',
        'description' => 'Zkuste obnovit stránku.<br>Když to nepomůže, vraťte se k nám prosím později.',
        'anchor' => 'Obnovit stránku'
    ],
];
$message = $messages[$locale] ?? $message['cs'];

?>

<!DOCTYPE html><!-- "' --></script></style></noscript></xmp>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />

<meta name="robots" content="noindex">
<title><?php echo $message['title']; ?> | JK Jitka Kudlackova Jewels</title>
<link rel="stylesheet" href="/assets/front/css/main.min.css?v1" />

<link rel="apple-touch-icon" sizes="57x57" href="/assets/front/images/favicon/apple-touch-icon-57x57.png" />
<link rel="apple-touch-icon" sizes="60x60" href="/assets/front/images/favicon/apple-touch-icon-60x60.png" />
<link rel="apple-touch-icon" sizes="72x72" href="/assets/front/images/favicon/apple-touch-icon-72x72.png" />
<link rel="apple-touch-icon" sizes="76x76" href="/assets/front/images/favicon/apple-touch-icon-76x76.png" />
<link rel="apple-touch-icon" sizes="114x114" href="/assets/front/images/favicon/apple-touch-icon-114x114.png" />
<link rel="apple-touch-icon" sizes="120x120" href="/assets/front/images/favicon/apple-touch-icon-120x120.png" />
<link rel="apple-touch-icon" sizes="144x144" href="/assets/front/images/favicon/apple-touch-icon-144x144.png" />
<link rel="apple-touch-icon" sizes="152x152" href="/assets/front/images/favicon/apple-touch-icon-152x152.png" />
<link rel="apple-touch-icon" sizes="180x180" href="/assets/front/images/favicon/apple-touch-icon-180x180.png" />
<link rel="icon" type="image/png" href="/assets/front/images/favicon/favicon-32x32.png" sizes="32x32" />
<link rel="icon" type="image/png" href="/assets/front/images/favicon/android-chrome-192x192.png" sizes="192x192" />
<link rel="icon" type="image/png" href="/assets/front/images/favicon/favicon-16x16.png" sizes="16x16" />
<link rel="mask-icon" href="/assets/front/images/favicon/safari-pinned-tab.svg" color="#ffffff" />
<link rel="shortcut icon" href="/assets/front/images/favicon/favicon.ico" />

<div class="Container Container--slim u-textCenter u-mt--50">
	<h1><?php echo $message['h1']; ?></h1>

	<p><?php echo $message['description']; ?></p>

    <h2><?php echo $message['action']['title']; ?></h2>
    <p><?php echo $message['action']['description']; ?></p>

    <div class="u-pt--30">
        <a href="<?php echo (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";; ?>" class="Button"><?php echo $message['action']['anchor']; ?></a>
    </div>
</div>
