CREATE TABLE `shopping_cart` (
  `sc_id` int(11) NOT NULL AUTO_INCREMENT,
  `sc_ip_address` varchar(50) NOT NULL,
  `sc_customer_id` int(11) DEFAULT NULL,
  `sc_name` varchar(255) DEFAULT NULL,
  `sc_email` varchar(50) DEFAULT NULL,
  `sc_telephone` varchar(20) DEFAULT NULL,
  `sc_delivery_address` varchar(255) DEFAULT NULL,
  `sc_delivery_city` varchar(255) DEFAULT NULL,
  `sc_delivery_country` varchar(255) DEFAULT NULL,
  `sc_delivery_postal_code` tinyint(10) DEFAULT NULL,
  `sc_birthday_coupon` tinyint(1) NOT NULL DEFAULT '0',
  `sc_hash` varchar(32) NOT NULL,
  `sc_billing_name` varchar(50) DEFAULT NULL,
  `sc_billing_address` varchar(50) DEFAULT NULL,
  `sc_billing_city` varchar(50) DEFAULT NULL,
  `sc_billing_postal_code` varchar(50) DEFAULT NULL,
  `sc_billing_country` varchar(50) DEFAULT NULL,
  `sc_billing_in` varchar(50) DEFAULT NULL,
  `sc_billing_vat_id` varchar(50) DEFAULT NULL,
  `sc_billing_telephone` varchar(50) DEFAULT NULL,
  `sc_billing_email` varchar(50) DEFAULT NULL,
  `sc_billing_bank_account` varchar(50) DEFAULT NULL,
  `sc_comment` text,
  `sc_add_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sc_update_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`sc_id`),
  KEY `sc_customer_id` (`sc_customer_id`),
  CONSTRAINT `shopping_cart_ibfk_3` FOREIGN KEY (`sc_customer_id`) REFERENCES `customer` (`cus_id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;