CREATE TABLE `order_product` (
  `op_id` int(11) NOT NULL AUTO_INCREMENT,
  `op_order_id` int(11) NOT NULL,
  `op_product_id` int(11) DEFAULT NULL,
  `op_external_system_id` int(11) DEFAULT NULL,
  `op_code` varchar(50) NOT NULL,
  `op_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL,
  `op_quantity` smallint(11) NOT NULL,
  `op_discount` decimal(19,3) NOT NULL,
  `op_unit_price` decimal(19,3) NOT NULL,
  `op_unit_price_without_vat` decimal(19,3) NOT NULL,
  `op_unit_price_before_discount` decimal(19,3) NOT NULL,
  `op_unit_price_before_discount_without_vat` decimal(19,3) NOT NULL,
  `op_summary_price` decimal(19,3) NOT NULL,
  `op_summary_price_without_vat` decimal(19,3) NOT NULL,
  `op_summary_price_before_discount` decimal(19,3) NOT NULL,
  `op_summary_price_before_discount_without_vat` decimal(19,3) NOT NULL,
  `op_surcharge_percent` decimal(19,3) DEFAULT NULL,
  `op_surcharge` decimal(19,3) DEFAULT NULL,
  `op_surcharge_without_vat` decimal(19,3) DEFAULT NULL,
  `op_vat` decimal(19,3) NOT NULL,
  `op_in_stock` tinyint(1) NOT NULL,
  `op_production_time` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`op_id`),
  KEY `op_order_id` (`op_order_id`),
  KEY `op_product_id` (`op_product_id`),
  CONSTRAINT `order_product_ibfk_1` FOREIGN KEY (`op_order_id`) REFERENCES `order` (`o_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `order_product_ibfk_2` FOREIGN KEY (`op_product_id`) REFERENCES `product` (`p_id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;