CREATE TABLE `product_variant_v2` (
  `pv_id` int(11) NOT NULL AUTO_INCREMENT,
  `pv_product_id` int(11) NOT NULL,
  `pv_product_parameter_id` int(11) NOT NULL,
  `pv_product_parameter_relation_id` int(11) NOT NULL,
  `pv_product_variant_id` int(11) NOT NULL,
  `pv_product_variant_parameter_id` int(11) NOT NULL,
  `pv_product_variant_parameter_relation_id` int(11) NOT NULL,
  `pv_parameter_group_id` int(11) NOT NULL,
  `pv_add_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`pv_id`),
  UNIQUE KEY `pv_product_id` (`pv_product_id`,`pv_product_variant_id`,`pv_product_variant_parameter_id`),
  KEY `pv_product_parameter_id` (`pv_product_parameter_id`),
  KEY `pv_product_parameter_relation_id` (`pv_product_parameter_relation_id`),
  KEY `pv_product_variant_id` (`pv_product_variant_id`),
  KEY `pv_product_variant_parameter_id` (`pv_product_variant_parameter_id`),
  KEY `pv_product_variant_parameter_relation_id` (`pv_product_variant_parameter_relation_id`),
  KEY `pv_parameter_group_id` (`pv_parameter_group_id`),
  CONSTRAINT `product_variant_v2_ibfk_1` FOREIGN KEY (`pv_product_id`) REFERENCES `product` (`p_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `product_variant_v2_ibfk_2` FOREIGN KEY (`pv_product_parameter_id`) REFERENCES `product_parameter` (`pp_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `product_variant_v2_ibfk_3` FOREIGN KEY (`pv_product_parameter_relation_id`) REFERENCES `product_parameter_relationship` (`ppr_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `product_variant_v2_ibfk_4` FOREIGN KEY (`pv_product_variant_id`) REFERENCES `product` (`p_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `product_variant_v2_ibfk_5` FOREIGN KEY (`pv_product_variant_parameter_id`) REFERENCES `product_parameter` (`pp_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `product_variant_v2_ibfk_6` FOREIGN KEY (`pv_product_variant_parameter_relation_id`) REFERENCES `product_parameter_relationship` (`ppr_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `product_variant_v2_ibfk_7` FOREIGN KEY (`pv_parameter_group_id`) REFERENCES `product_parameter_group` (`ppg_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;