CREATE TABLE `order` (
  `o_id` int(11) NOT NULL AUTO_INCREMENT,
  `o_code` char(12) NOT NULL,
  `o_customer_id` int(11) DEFAULT NULL,
  `o_customer_external_system_id` int(11) DEFAULT NULL,
  `o_customer_first_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL,
  `o_customer_last_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL,
  `o_customer_email` varchar(50) NOT NULL,
  `o_customer_telephone` varchar(20) NOT NULL,
  `o_billing_address_street` varchar(35) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL,
  `o_billing_address_city` varchar(35) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL,
  `o_billing_address_postcode` char(5) NOT NULL,
  `o_billing_address_country` char(2) NOT NULL,
  `o_delivery_address_first_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_czech_ci,
  `o_delivery_address_last_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_czech_ci DEFAULT NULL,
  `o_delivery_address_company` varchar(50) CHARACTER SET utf8 COLLATE utf8_czech_ci DEFAULT NULL,
  `o_delivery_address_street` varchar(35) CHARACTER SET utf8 COLLATE utf8_czech_ci DEFAULT NULL,
  `o_delivery_address_city` varchar(35) CHARACTER SET utf8 COLLATE utf8_czech_ci DEFAULT NULL,
  `o_delivery_address_postcode` char(5) DEFAULT NULL,
  `o_delivery_address_country` char(2) DEFAULT NULL,
  `o_payment_id` int(11) DEFAULT NULL,
  `o_payment_external_system_id` int(11) NOT NULL,
  `o_payment_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL,
  `o_payment_price` decimal(19,3) NOT NULL,
  `o_payment_vat` decimal(19,3) NOT NULL,
  `o_delivery_id` int(11) DEFAULT NULL,
  `o_delivery_external_system_id` int(11) NOT NULL,
  `o_delivery_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL,
  `o_delivery_price` decimal(19,3) NOT NULL,
  `o_delivery_vat` decimal(19,3) NOT NULL,
  `o_delivery_information` varchar(10) DEFAULT NULL,
  `o_delivery_tracking_code` varchar(20) DEFAULT NULL,
  `o_summary_price` decimal(19,3) NOT NULL,
  `o_summary_price_without_vat` decimal(19,3) NOT NULL,
  `o_summary_price_before_discount` decimal(19,3) NOT NULL,
  `o_summary_price_before_discount_without_vat` decimal(19,3) NOT NULL,
  `o_comment` text CHARACTER SET utf8 COLLATE utf8_czech_ci,
  `o_state` varchar(20) NOT NULL,
  `o_add_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `o_update_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`o_id`),
  UNIQUE KEY `o_code` (`o_code`),
  KEY `o_customer_id` (`o_customer_id`),
  KEY `o_payment_id` (`o_payment_id`),
  KEY `o_delivery_id` (`o_delivery_id`),
  CONSTRAINT `order_ibfk_1` FOREIGN KEY (`o_customer_id`) REFERENCES `customer` (`cus_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `order_ibfk_2` FOREIGN KEY (`o_payment_id`) REFERENCES `payment` (`py_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `order_ibfk_3` FOREIGN KEY (`o_delivery_id`) REFERENCES `delivery` (`d_id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;